-- Cleanup orphaned sequences
DROP SEQUENCE IF EXISTS chats_id_seq CASCADE;
DROP SEQUENCE IF EXISTS frames_id_seq CASCADE;
DROP SEQUENCE IF EXISTS projects_id_seq CASCADE;
DROP SEQUENCE IF EXISTS users_id_seq CASCADE;

-- Drop existing tables
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS frames CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS users CASCADE;
